### ISSUE TITLE
"<template>" is a reserved tag for Meteor, it should provide an alternative!

### ISSUE THREAD

**Issue by thearabbit** [Akryum/vue-meteor#169]
I problem when using `Table of Vuetify`.
```js
<template>
  <v-data-table
      v-bind:headers="headers"
      v-model="items"
      v-bind:search="e3"
      :rows-per-page-items="[10,20]"
    >
    <template slot="items" scope="props">
      <td>{{ props.item.text }}</td>
      <td>{{ props.item.desc }}</td>
    </template>
  </v-data-table>
</template>
```
it should provide an alternative of `<template>`!

**Comment by Akryum** [comment]
This is a blaze issue (template tools). Please report it [here](https://github.com/meteor/blaze).

**Comment by nathantreid** [comment]
@akyrum what if we use `templateCompiler.parseComponent` from [vue-template-compiler](https://www.npmjs.com/package/vue-template-compiler#compilerparsecomponentfile-options) instead of using `template tools`? It parses the source string that is sent in (the full contents of the `.vue` file) and returns an object that is very similar to the structure of `this.component` in `tag-handler.js`.

We just ran into this issue and I was able to get it working by doing that - it turned out to be a relatively small change thanks to how you've written the tag handler. I'd be happy to make a PR.
