### ISSUE TITLE
Buffer not defined error with Meteor 1.5-beta.17+

### ISSUE THREAD

**Issue by nathantreid** [Akryum/vue-meteor#179]
In Meteor 1.5, the Buffer polyfill will no longer being included by default (as noted here: https://github.com/meteor/meteor/issues/8645).
This breaks `vue-component-dev-client`.
The fix is to add this line to load the buffer yourself prior to import from `node_modules`:
```js
global.Buffer = global.Buffer || require("buffer").Buffer;
```
I fixed it locally by creating a `buffer.js` file with the above line and making it the first import in `dev-client.js`.

**Comment by eybarta** [comment]
hey @nathantreid, sorry for my noobieness on this :-\

I tried doing what you did, added buffer.js to same folder as dev-client.js and importing it before everything, but I get an ecmascript error when trying to build..

Could you show me the syntax you're using and the location of buffer.js ? don't you need to 'export' the buffer in order to 'import' it?

thank u

**Comment by nathantreid** [comment]
@eybarta, this is what I did:

1. buffer.js
```js
global.Buffer = global.Buffer || require("buffer").Buffer;
```
2. dev-client.js
```js
import './buffer';
// ... rest of file ...
```

**Comment by eybarta** [comment]
@nathantreid thanks for your reply.. that's what I tried but didn't work for me, I downgraded meteor for now. thx.

**Comment by thearabbit** [comment]
Now `Meteor 1.5` is released.
